## Visualise stokes annulus model (flow etc)

In [1]:
# to fix trame issue
import nest_asyncio
nest_asyncio.apply()
import os

In [2]:
import petsc4py
import underworld3 as uw
import numpy as np
import sympy

In [3]:
ls -trl output/annulus/ | tail

total 0
drwxr-xr-x  824 lmoresi  staff  26368 Aug 13 09:44 Ra1e5/


In [4]:
ls -trl output/annulus/Ra1e5/ | tail

-rw-r--r--  1 lmoresi  staff   88760 Aug 12 16:36 annulus_ckpt.mesh.U.00068.h5
-rw-r--r--  1 lmoresi  staff   37048 Aug 12 16:36 annulus_ckpt.mesh.P.00068.h5
-rw-r--r--  1 lmoresi  staff   69160 Aug 12 16:36 annulus_ckpt.mesh.T.00068.h5
-rw-r--r--  1 lmoresi  staff    3030 Aug 12 16:36 annulus_ckpt.mesh.00068.xdmf
-rw-r--r--  1 lmoresi  staff   88760 Aug 12 16:36 annulus_ckpt.mesh.U.00069.h5
-rw-r--r--  1 lmoresi  staff   37048 Aug 12 16:36 annulus_ckpt.mesh.P.00069.h5
-rw-r--r--  1 lmoresi  staff   69160 Aug 12 16:36 annulus_ckpt.mesh.T.00069.h5
-rw-r--r--  1 lmoresi  staff    3030 Aug 12 16:36 annulus_ckpt.mesh.00069.xdmf
-rw-r--r--  1 lmoresi  staff  381460 Aug 13 09:43 annulus_ckpt0.png
-rw-r--r--  1 lmoresi  staff  711720 Aug 13 09:43 annulus_ckpt10.png


In [5]:
checkpoint_dir = "output/annulus/Ra1e5"
checkpoint_base = f"annulus_ckpt"
meshfile = os.path.join(checkpoint_dir, checkpoint_base) + ".mesh.00000.h5"

In [6]:
r_i = 0.5
r_o = 1.0

mesh = uw.discretisation.Mesh(meshfile, 
                              coordinate_system_type=uw.coordinates.CoordinateSystemType.CYLINDRICAL2D,
                              refinement=0)

# mesh = uw.meshing.Annulus(
#     radiusInner=r_i, 
#     radiusOuter=r_o, 
#     cellSize=1/20, 
#     degree=1, 
#     qdegree=3, 
# )



# mesh = uw.meshing.Annulus(
#     radiusInner=r_i, 
#     radiusOuter=r_o, 
#     cellSize=1/24, 
#     degree=1, 
#     qdegree=3, 
# )

x = mesh.N.x
y = mesh.N.y

r = sympy.sqrt(x**2 + y**2)  # cf radius_fn which is 0->1
th = sympy.atan2(y + 1.0e-5, x + 1.0e-5)

v_soln = uw.discretisation.MeshVariable("U", mesh, mesh.dim, degree=1)
t_soln = uw.discretisation.MeshVariable("T", mesh, 1, degree=2)
flux = uw.discretisation.MeshVariable(r"dTdz", mesh, 1, degree=2)

In [7]:
step=10
v_soln.read_timestep(checkpoint_base, "U", step, outputPath=checkpoint_dir)
t_soln.read_timestep(checkpoint_base, "T", step, outputPath=checkpoint_dir)




Local points: 484
Distance N 0:10
[0.         0.00110973 0.00170484 0.00170484]
[   0  790 1236 1250]
[ 9.00374364e-02  6.48567655e+01  1.90861701e+02 -1.92623646e+02]
[0.         0.00110973 0.00170484 0.00170484]
[   1  792 1237 1251]
[-9.07339783e-02 -6.46450727e+01 -1.91147639e+02  1.92924161e+02]
[0.         0.00157398 0.00170775 0.00170775]
[   2 1654 1676  990]
[ 8.40318956e-02 -3.92603341e+01 -1.17415025e+02  7.68670004e+01]
[0.         0.00157398 0.00170775 0.00170775]
[   3 1655 1678  993]
[-8.36816948e-02  3.93211671e+01  1.17702178e+02 -7.76309220e+01]
[0.         0.00150443 0.00170484 0.00170484]
[   4  794 1250 1226]
[-382.26694945 -423.59512406 -192.62364639 -549.84856769]
[0.         0.00154515 0.00168277 0.00170484]
[   5  855  854 1226]
[-704.41906409 -644.36684325 -556.78123136 -549.84856769]
[0.         0.00154515 0.00170484 0.00170484]
[   6  859  858 1242]
[-837.87321868 -657.11511307 -505.04489431 -699.1042785 ]
[0.         0.00155317 0.00170484 0.00170484]
[   7 

In [8]:
import pyvista as pv
import underworld3.visualisation as vis


t_cloud = uw.visualisation.meshVariable_to_pv_cloud(t_soln)
t_cloud.point_data["T"] = vis.scalar_fn_to_pv_points(t_cloud, t_soln.sym)
t_mesh = t_cloud.delaunay_2d(alpha=1/10)
pl = pv.Plotter(window_size=[1000, 1000])

pl.add_mesh(
        t_mesh,
        cmap="RdBu_r",
        edge_color="Black",
        show_edges=False)

pl.show()

Local points: 1822
Distance N 0:10
[0.         0.00110973 0.00170484]
[   0  790 1236]
[0.99998223 0.40805896 0.99996481]
[0.         0.00110973 0.00170484]
[   1  792 1237]
[0.99998218 0.40635468 0.99996475]
[0.         0.00157398 0.00170775]
[   2 1654 1676]
[1.63024801e-05 3.16502669e-01 1.50082578e-05]
[0.         0.00157398 0.00170775]
[   3 1655 1678]
[1.64793322e-05 3.19537224e-01 1.51140030e-05]
[0.         0.00150443 0.00170484]
[   4  794 1250]
[0.99998627 0.46758313 0.99998579]
[0.         0.00154515 0.00168277]
[  5 855 854]
[0.99997726 0.57385633 0.51198316]
[0.         0.00154515 0.00170484]
[  6 859 858]
[0.99998314 0.62172498 0.70111253]
[0.         0.00155317 0.00170484]
[  7 541 540]
[0.99999444 0.95891965 0.81353201]
[0.         0.00170484 0.00170484]
[   8 1238  778]
[1.00000012 0.99999342 1.00000013]
[0.         0.00165877 0.00170484]
[   9  810 1238]
[0.99999111 0.63806463 0.99999342]
Weights [[1000054.23626263]
 [1000054.23626263]
 [1000049.40300332]
 [1000049.40

Widget(value='<iframe id="pyvista-jupyter_trame__template_P_0x1521f0110_0" src="http://localhost:8889/trame-ju…

In [9]:
0/0

ZeroDivisionError: division by zero

In [ ]:
steps = range(0,20,10)

In [ ]:
import mpi4py
import pyvista as pv
import underworld3.visualisation as vis

pl = pv.Plotter(window_size=[1000, 1000])

for step in steps:

    try:
        v_soln.read_timestep(checkpoint_base, "U", step, outputPath=checkpoint_dir)
        t_soln.read_timestep(checkpoint_base, "T", step, outputPath=checkpoint_dir)
        print(f"Plotting step {step}")

    except:
        print(f"Failed to read step {step} correctly")
        continue

    pl.clear()

    pvmesh = vis.mesh_to_pv_mesh(mesh)
    pvmesh.point_data["T"] = vis.scalar_fn_to_pv_points(pvmesh, t_soln.sym[0])
    pvmesh.point_data["V"] = vis.vector_fn_to_pv_points(pvmesh, v_soln.sym)
    
    velocity_points = vis.meshVariable_to_pv_cloud(v_soln)
    velocity_points.point_data["V"] = vis.vector_fn_to_pv_points(velocity_points, v_soln.sym)

    temperature_points = vis.meshVariable_to_pv_cloud(t_soln)
    temperature_points.point_data["T"] = vis.scalar_fn_to_pv_points(temperature_points, t_soln.sym)

    # point sources at cell centres
    skip = 15
    points = np.zeros((mesh._centroids[::skip].shape[0], 3))
    points[:, 0] = mesh._centroids[::skip, 0]
    points[:, 1] = mesh._centroids[::skip, 1]
    point_cloud = pv.PolyData(points)
    
    pvstream = pvmesh.streamlines_from_source(
        point_cloud,
        vectors="V",
        integration_direction="both",
        max_time=1,
        surface_streamlines=True,
    )
    
    pl.add_mesh(
        pvmesh,
        cmap="RdBu_r",
        edge_color="Black",
        show_edges=False,
        scalars="T",
        use_transparency=False,
        opacity=1.0,
        show_scalar_bar=False
    )
    
    pl.add_mesh(pvstream, opacity=0.4, show_scalar_bar=False)    
    pl.add_points(point_cloud, color="White", point_size=3.0, opacity=0.25)
    # pl.add_points(temperature_points, 
    #               render_points_as_spheres=True,
    #               cmap="RdBu_r", scalars="T", 
    #               point_size=5.0, opacity=1,
    #               show_scalar_bar=False,
    #              )


    
    imagefile = os.path.join(checkpoint_dir, checkpoint_base) + f"{step}.png"
    
    pl.screenshot(filename=imagefile, window_size=(1000, 1000), return_img=False)



In [ ]:
pl.show()

In [ ]:
## Calculate heat flux, evaluate at surface — proxy for boundary layer thickness

In [ ]:
flux_solver = uw.systems.Projection(mesh, flux)

# Conductive flux only !
radial_flux = -mesh.vector.gradient(t_soln.sym[0]).dot(mesh.CoordinateSystem.unit_e_0)
radial_flux *= sympy.exp(-100*(r-1)**2) 

flux_solver.uw_function = radial_flux
flux_solver.smoothing = 1.0e-3
flux_solver.solve()

In [ ]:
import mpi4py
import pyvista as pv
import underworld3.visualisation as vis

pvmesh = vis.mesh_to_pv_mesh(mesh)
pvmesh.point_data["dTdz"] = vis.scalar_fn_to_pv_points(pvmesh, flux.sym[0])
pvmesh.point_data["V"] = vis.vector_fn_to_pv_points(pvmesh, v_soln.sym)
pvmesh.point_data["V"] -= pvmesh.point_data["V"].mean()

velocity_points = vis.meshVariable_to_pv_cloud(v_soln)
velocity_points.point_data["V"] = vis.vector_fn_to_pv_points(velocity_points, v_soln.sym)

# point sources at cell centres
skip = 1
points = np.zeros((mesh._centroids[::skip].shape[0], 3))
points[:, 0] = mesh._centroids[::skip, 0]
points[:, 1] = mesh._centroids[::skip, 1]
point_cloud = pv.PolyData(points)

pvstream = pvmesh.streamlines_from_source(
    point_cloud,
    vectors="V",
    integration_direction="both",
    max_time=0.5,
)

pl = pv.Plotter(window_size=[1000, 1000])

pl.add_mesh(
    pvmesh,
    cmap="Reds",
    edge_color="Black",
    show_edges=True,
    scalars="dTdz",
    use_transparency=False,
    opacity=1.0,
)

# 
# pl.add_mesh(pvmesh, "Black", "wireframe",  opacity=0.1)

# pl.add_points(point_cloud, color="White", point_size=3.0, opacity=0.25)

# pl.add_arrows(velocity_points.points, velocity_points.point_data["V"], mag=0.0001, show_scalar_bar=True)
pl.add_mesh(pvstream, opacity=0.4, show_scalar_bar=False)
    
# pl.remove_scalar_bar("V")

imagefile = os.path.join(checkpoint_dir, checkpoint_base) + f"{step}.png"

pl.screenshot(filename=imagefile, window_size=(1000, 1000), return_img=False)
# OR


In [ ]:
pl.show()

In [ ]:
0/0